// flow-typed signature: fe4a814e57c21837e7082b5e8a15e459
// flow-typed version: <<STUB>>/@oneblink/sdk_v^0.4.5/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oneblink/sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oneblink/sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oneblink/sdk/classes/Forms' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/FormsApps' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/Jobs' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/Keys' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/Organisations' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/classes/TeamMembers' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/axios_v0.18.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/npm/jest_v24.x.x' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/flow-typed/types' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/forms-schema' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/forms-validation' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-form-element' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-form-url' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/generate-jwt' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/one-blink-api-error-handler' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/one-blink-api' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/pre-fill-data' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/retrieve-submission-data' {
  declare module.exports: any;
}

declare module '@oneblink/sdk/lib/tenant' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oneblink/sdk/classes/Forms.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Forms'>;
}
declare module '@oneblink/sdk/classes/FormsApps.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/FormsApps'>;
}
declare module '@oneblink/sdk/classes/Jobs.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Jobs'>;
}
declare module '@oneblink/sdk/classes/Keys.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Keys'>;
}
declare module '@oneblink/sdk/classes/Organisations.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/Organisations'>;
}
declare module '@oneblink/sdk/classes/TeamMembers.js' {
  declare module.exports: $Exports<'@oneblink/sdk/classes/TeamMembers'>;
}
declare module '@oneblink/sdk/flow-typed/npm/axios_v0.18.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/axios_v0.18.x'>;
}
declare module '@oneblink/sdk/flow-typed/npm/jest_v24.x.x.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/npm/jest_v24.x.x'>;
}
declare module '@oneblink/sdk/flow-typed/types.js' {
  declare module.exports: $Exports<'@oneblink/sdk/flow-typed/types'>;
}
declare module '@oneblink/sdk/index' {
  declare module.exports: $Exports<'@oneblink/sdk'>;
}
declare module '@oneblink/sdk/index.js' {
  declare module.exports: $Exports<'@oneblink/sdk'>;
}
declare module '@oneblink/sdk/lib/forms-schema.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/forms-schema'>;
}
declare module '@oneblink/sdk/lib/forms-validation.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/forms-validation'>;
}
declare module '@oneblink/sdk/lib/generate-form-element.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-form-element'>;
}
declare module '@oneblink/sdk/lib/generate-form-url.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-form-url'>;
}
declare module '@oneblink/sdk/lib/generate-jwt.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/generate-jwt'>;
}
declare module '@oneblink/sdk/lib/one-blink-api-error-handler.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/one-blink-api-error-handler'>;
}
declare module '@oneblink/sdk/lib/one-blink-api.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/one-blink-api'>;
}
declare module '@oneblink/sdk/lib/pre-fill-data.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/pre-fill-data'>;
}
declare module '@oneblink/sdk/lib/retrieve-submission-data.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/retrieve-submission-data'>;
}
declare module '@oneblink/sdk/lib/tenant.js' {
  declare module.exports: $Exports<'@oneblink/sdk/lib/tenant'>;
}
