language: node_js
node_js:
  - '12'
sudo: false
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global npm@6.x.x
  - npm ci

deploy:
  - provider: script
    script: bash scripts/deploy.sh test
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.sh prod
    on:
      tags: true
